### ISSUE TITLE
Choix du premier livre

### ISSUE THREAD

**Issue by Mayeu** [ftbc/organisation#1]
Je propose de commencer par [The Pragmatic Programmer: From Journeyman to Master](https://pragprog.com/book/tpp/the-pragmatic-programmer) (~320 pages, 8 chapitres), est-ce que ça convient à tous le monde ? Comme c'est un classique peut-être que trop de personnes l'ont déjà lu. Faite le savoir et faite vos autres propositions dans ce ticket :)

**Comment by martinmaillard** [comment]
J'avais commencé mais jamais terminé, ce sera l'occasion :)

**Comment by supcik** [comment]
Pour moi c'est OK. A part ça (ou après ça) je propose "Hackers & Painters" de Paul Graham (https://en.wikipedia.org/wiki/Hackers_%26_Painters)

**Comment by Mayeu** [comment]
Je ferme ce ticket vu que le choix du _Pragmatic Programmer_ est arrêté.
