### ISSUE TITLE
Choix de la date et lieu

### ISSUE THREAD

**Issue by Mayeu** [ftbc/organisation#2]
Pour le lieu, je propose le [Colab de Fribourg](http://www.colab-fribourg.ch/), je pense qu'on sera plusieurs à avoir les clés du lieux.

Pour la première séance, si on arrive à le faire début mars ça serai pas mal je pense :)

Pour le jour de la rencontre et horaire, dans mon cas je suis indisponible :
- le lundi toute la journée
- le mercredi soir

Le colab est indisponible :
- le 3ième jeudi de chaque mois il y a le [FROSC](https://secure.frosc.ch/)
- le 3ième samedi de chaque mois il y a les [Café vie privée](https://cryptofribourg.ch)
- le dernier jeudi de chaque mois il y a les [Tech Meetings](http://www.techmeetings.ch/)

Quels sont vos propositions et disponibilités ? Évidement rien n'empêchera plus tard de changer tout ça :)

**Comment by Mayeu** [comment]
Est-ce que ça convient à la majorité si on fixe le premier rendez-vous jeudi 12 mars à 18h au Colab ? (On pourra discuter d'un autre jour de réunion sur le moment)

Le premier chapitre du _Pragmatic programmer_ faisant 25 pages, je propose de viser la lecture des chapitres 1 et 2 pour cette première séance, et on adaptera pour la quantité de lecture pour la suivante :)

Cela conviendrais au plus grand nombre ?

**Comment by martinmaillard** [comment]
C'est ok pour moi.

**Comment by Mayeu** [comment]
poke @supcik, @derlin, @damieng002 ? :)

**Comment by Goopil** [comment]
Pas dispo les jeudi. Ca vas pas m'empecher de lire par contre ;)

**Comment by Mayeu** [comment]
La première séance a eu lieu, je ferme ce ticket.

Rendez vous dans le ticket #6 pour discuter la future date fixe.
