### ISSUE TITLE
Passage de la séance aux mardi au lieu de jeudi

### ISSUE THREAD

**Issue by Mayeu** [ftbc/organisation#6]
Les deux prochains jeudi sont pris par le FROSC puis le TechMeeting.                            

Est-ce que ça convient de passer les séances de manière fixe au mardi ? Ça évitera d'avoir à bouger la séance de temps à autres.

J'en ai parlé à Philippe pour savoir si on pouvais profiter du Colab ces soirs là, il est d'accord tant qu'on attends que le Colab soit vide pour démarrer (ce qui est le cas 99% du temps à 18h). Sinon on peut toujours démarrer dans la petite salle de réunion puis migrer dans le colab (mais 4 personnes seulement). Il me fait aussi dire qu'on peut louer la grande salle de réunion (8 places assises, 20-/heures).

Attendre que le Colab soit vide me parait être la meilleur solution.

Donc qu'est ce que vous dites de :
- passez la séance à mardi
- être d'accord sur le fait d'attendre (mais ça ne devrait quasiment jamais arriver) que le Colab soit vide pour démarrer.

**Comment by vhf** [comment]
OK pour les mardi soirs 18h.

**Comment by martinmaillard** [comment]
Ok pour moi aussi :)

**Comment by Mayeu** [comment]
:+1:

**Comment by Mayeu** [comment]
Vu que mardi c'est maintenant dans 2 jours, je propose de valider ces choix, et fermer ce ticket.

J'ai modifié le [README](https://github.com/ftbc/organisation#fribourg-technical-book-club) avec le planning actuel, et j'en ai profité pour spammer [techup](http://techup.ch) avec [nos séances](http://techup.ch/canton/FR) :)

À mardi donc !
