### ISSUE TITLE
Séance du 7 avril, possible de déplacer au lundi 6 ?

### ISSUE THREAD

**Issue by Mayeu** [ftbc/organisation#8]
Salut à tous,

Lors de la dernière séance je disais que je ne pourrais surement pas venir avant 18h30/40 du fait du décalage de ma journée à Bern du lundi au mardi. Par contre je suis en fait disponible le lundi 6 (lundi de Pâques) pour l'horaire habituel.

Est-ce que ça conviendrais de se voir lundi prochain au lieu de mardi du coup ?

**Comment by vhf** [comment]
Lundi me va aussi.

**Comment by martinmaillard** [comment]
Ok pour moi aussi

**Comment by Mayeu** [comment]
Cool, ba je déplace les différentes annonces :)
